server:
  port: 8090
spring:
  config:
    activate:
      on-profile: local
  application:
    name: hdi-rural-busca-bff-api

logging:
  file: hdi-rural-busca-bff.log
  org.hibernate: INFO

feign:
  client:
    config:
      default:
        connetionTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

rural-busca-bff:
  getToken:
    url: https://hdibr-gi-sandbox-am.insuremo.com
    username: hdibr.app
    password: eBao2014
  queryPolicy:
    url: https://sandbox-am-gw.insuremo.com/hdibr/1.0/hdibr-bff-app